### ISSUE TITLE
电小哥-用户充值方式途径无字段

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/51dianxiaoge#12]
1、充值途径：银行转账、POS刷卡、现金、其他、支票、账扣、冲正
2、流水账单内显示各充值途径

**Comment by ZSH-HSZ** [comment]
后台未配置 @kpse

**Comment by ZSH-HSZ** [comment]
后台未配置，这不是一个错误，请 @DXcheng 关闭 @kpse
