### ISSUE TITLE
电小鸽-房源“智能设备”绑定对话框仪表数量显示异常

### ISSUE THREAD

**Issue by DXcheng** [cloudenergy/51dianxiaoge#9]
![image](https://user-images.githubusercontent.com/27998601/39132038-79e8759a-4743-11e8-8971-ddbb31d70339.png)

**Comment by ZSH-HSZ** [comment]
@kpse 电表绑定的时候，接口返回的count数目不对

**Comment by ZSH-HSZ** [comment]
已修复 @DXcheng @kpse
